<a href="https://colab.research.google.com/github/shri-1805/Machine-Learning-Basics/blob/main/Linear_Regression1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Necessary Libraries

In [54]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [55]:
#read the data
df = pd.read_csv("50_Startups.csv")

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        108 non-null    float64
 1   Administration   108 non-null    float64
 2   Marketing Spend  108 non-null    float64
 3   State            108 non-null    object 
 4   Profit           108 non-null    float64
dtypes: float64(4), object(1)
memory usage: 4.3+ KB


In [57]:
df.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [58]:
# Label Encoder
df["State"].unique()
le=LabelEncoder()
df["State"]=le.fit_transform(df["State"])
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [59]:
# one hot encoder to predict profit of a startup Profit->dependent column
x =df.iloc[:,0:4].values
y=df.iloc[:,4:5].values


In [60]:
x.shape

(108, 4)

In [61]:
y.shape

(108, 1)

In [62]:
# hot rod - convert numerical data to categorical
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
z=one.fit_transform(x[:,3:4]).toarray()


In [63]:
x=np.delete(x,3,axis=1)
x.shape

(108, 3)

In [64]:
x=np.concatenate((z,x),axis=1)
x.shape

(108, 6)

In [65]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [66]:
x_train.shape

(86, 6)

In [67]:
x_test.shape

(22, 6)

In [68]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [69]:
ypred=lr.predict(x_test)
ypred

array([[ 48466.75433416],
       [134429.39628446],
       [ 76093.94745793],
       [181201.94746512],
       [113069.45110036],
       [134397.50337434],
       [128842.89457941],
       [159664.83856911],
       [116952.09718498],
       [ 46372.47771261],
       [102406.37641003],
       [115207.87076438],
       [ 48466.75433416],
       [119345.51846304],
       [ 88717.92542864],
       [127301.68084921],
       [127301.68084921],
       [ 91145.83032982],
       [ 58337.13774601],
       [146474.04747225],
       [149038.44713346],
       [152718.63782934]])

In [70]:
y_test

array([[ 64926.08],
       [146121.95],
       [ 90708.19],
       [191050.39],
       [108552.04],
       [144259.4 ],
       [124266.9 ],
       [155752.6 ],
       [126992.93],
       [ 42559.73],
       [101004.64],
       [110352.25],
       [ 64926.08],
       [111313.02],
       [ 89949.14],
       [134307.35],
       [134307.35],
       [ 96712.8 ],
       [ 49490.75],
       [129917.04],
       [132602.65],
       [152211.77]])

In [71]:
from sklearn.metrics import r2_score
acc=r2_score(ypred,y_test)
acc

0.9316315637551587

In [72]:
yp=lr.predict([[1,0,0,1221323,21323,321342]])
yp

array([[1012169.44199398]])